db_mysql_profile_name:
  type: mysql
  host: localhost
  port: 3306
  user: root
  pass: password
  database: example

db_pgsql_profile_name:
  type: postgresql
  host: localhost
  port: 5432
  user: postgres
  pass: password
  database: example